In [11]:
# Define a lotto number generator (as a function)
# Use random sampling to generate the result of 10 dice rolls (numbers between 1 and 6)
# Change the outcome to 0 if the number is under 4 (exclusive), and 1 if over 4 (inclusive)
# Use 'sum' to count all high numbers (face of 4 or above)

In [21]:
import numpy as np
def lotto_number_generator():
    a = [1,2,3,4,5,6]
    rolls = np.random.choice(a,10)
    print(rolls)
    no_high_numbers = sum([0 if roll<4 else 1 for roll in rolls])
    return no_high_numbers

In [22]:
lotto_number_generator()

[2 3 1 3 3 4 3 2 3 6]


2

In [23]:
lotto_number_generator()

[6 4 2 4 5 6 5 3 3 1]


6

In [24]:
lotto_number_generator()

[5 5 2 3 6 1 2 2 1 6]


4