# The Order Book

## When we implement an order book for some asset (coming as a homework assignment soon), we store customer's bids and asks. 

## These include for a bidder:
## &nbsp;&nbsp;&nbsp;&nbsp; the identity of the bidder,
## &nbsp;&nbsp;&nbsp;&nbsp; the price they are willing to pay,
## &nbsp;&nbsp;&nbsp;&nbsp; the number of units they want to buy
## &nbsp;&nbsp;&nbsp;&nbsp; the timestamp for which the order is received.

## And for an asker:
## &nbsp;&nbsp;&nbsp;&nbsp; the identity of the asker,
## &nbsp;&nbsp;&nbsp;&nbsp; the price at whcih they are willing to sell,
## &nbsp;&nbsp;&nbsp;&nbsp; the number of units they want to sell
## &nbsp;&nbsp;&nbsp;&nbsp; the timestamp for which the order is received.


## It is the job of the order book maintainer to match buyers and sellers.
## How is this done? As soon as there is a list of bidder/asker pairs with bidders price at or above an  asker's price, a trade should take place. 
## But which trade happens first?

## A rule is needed for deciding whose bid is accepted first, and whose ask is accepted first.

## Here is a typical rule for bidders:

## &nbsp;&nbsp;&nbsp;&nbsp; The highest priced bid gets highest priority.
## &nbsp;&nbsp;&nbsp;&nbsp; In cases of ties, the bid with the earlies time stamp gets highest priority.

## And for askers:
## &nbsp;&nbsp;&nbsp;&nbsp; The lowest price asked gets highest priority.
## &nbsp;&nbsp;&nbsp;&nbsp; In cases of ties, the ask with the earlies time stamp gets highest priority.




# Priority Queues in Python

## A priority queue is a collection that objects can be added to one at a time. 

## For some objects (like ints or floats) there is a natural ordering, so priority is determined using the usual ordering (lower numbers get first priority. 

## We can put things in the queue and get things out of the queue.

## To illustrate, lets create a list of random numbers and put them into the queue.


In [1]:
import numpy as np
import queue

PQ=queue.PriorityQueue() # create a priorty queue

L=np.random.choice(range(15),size=15)
print(L)


for x in L:
    PQ.put(x)

[12  1  5  4  3  8  3  4  6 13 12  0 11  4  5]


## Now we pop from the queue in order of priority. When we do a get, the element with the highest priority is removed from the queue.

In [2]:
while not PQ.empty():
    x=PQ.get()
    print(x)

0
1
3
3
4
4
4
5
5
6
8
11
12
12
13


## If we want to inspect a queue, we need to be careful because the get operation removes the element from the queue.

## One way to inspect the queue is to remove elements one at a time, store them in a list, then move them back into the queue.

In [6]:
import numpy as np
import queue

#
# create the queue and load stuff into it
#
PQ=queue.PriorityQueue()
L=np.random.choice(range(15),size=15)
print(L)
for x in L:
    PQ.put(x)
    
#
# remove one at a time and store in a list
#
PQ2=queue.PriorityQueue()
L=[]
while not PQ.empty():
    x=PQ.get()
    PQ2.put(x)
    L.append(x)
print(L)
#
# put the list elements back in the queue
#
while not PQ2.empty():
    x=PQ2.get()
    PQ.put(x)


print(L)

[11 14  9 14  3 12 11  0  3 10  5 13  0  0  5]
[0, 0, 0, 3, 3, 5, 5, 9, 10, 11, 11, 12, 13, 14, 14]
[0, 0, 0, 3, 3, 5, 5, 9, 10, 11, 11, 12, 13, 14, 14]


In [ ]:
## So here is a function to make a list (in priority order) from a priority queue and reload it.

In [21]:
def list_from_queue(PQ):
    L=[]
    while not PQ.empty():
        L.append(PQ.get())
    for x in L:
        PQ.put(x)
    return(L,PQ)
#
# Create and load a priority queue
#
PQ=queue.PriorityQueue()
L=np.random.choice(range(15),size=15)
print(L)
for x in L:
    PQ.put(x)
#
# Get list from queue
#   
L,PQ=list_from_queue(PQ)
print(L)

[13 13  0  0  9  8  2 12 13  0 13  3 10  6  2]
[0, 0, 0, 2, 2, 3, 6, 8, 9, 10, 12, 13, 13, 13, 13]


## How do we create an alternative ordering of elements for a queue?

## The ordering is determined by calling the \_\_lt\_\_ (less than) method for a pair of objects O1 and O2 using a call like:
## &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; O1.\_\_lt\_\_(O2)

## The O1 will receive higher priority than O2 if O1.\_\_lt\_\_(O2) yields True.

## To add an object to the queue, we call the _put_ method for the queue.

## To get the highest priority object from the queue and remove it we call the _get_ method for the queue.

## To determine the number of objects in the queue, we can use the .qsize() method.

## To see the highest priority object without removing it, we can use the .queue[0] attribute. 

## Important note: the objects are available as .queue[0],.queue[1],....,.queue[n-1] but these are **not** in order by priority.

## In the following example, we consider a class of objects with a single slot for a numerical _value_.

In [7]:
import queue as Q
import numpy as np

#
# Create a class of things to put in the queue.
#
class thing:
    __slots__=("value")
    def __init__(self,value):
        self.value=value
    
    def __lt__(self,other):
        if self.value>=other.value:
            return(True)
        return(False)
    def __str__(self):
        return("   "+str(self.value))
    
#
# Create an instance of a priority queue
#
PQ=Q.PriorityQueue()
#
# Add some things to the queue 
#
print("Adding to the queue:")
for i in range(5):
    v=np.random.normal(100,10,1)[0]
    t=thing(v)
    PQ.put(t)
    print("   value of thing added = " + str(v))
print("Number of things in the queue = " + str(PQ.qsize()))
#
# Print the elements of the queue.
# This doesn't modify contents of the queue.
#
n=PQ.qsize()
print("Printing queue contents without modifying it:")
for i in range(n):
    print(PQ.queue[i])
print("Number of things in the queue = " + str(PQ.qsize()))
#
# Is queue empty?
#
if PQ.empty():
    print("queue is empty")
else:
    print("queue is non-empty")
#
# Get the elements one at a time.
#
while not PQ.empty():
    v=PQ.get()
    print(v)
    print("Number of things in queue = " + str(PQ.qsize()))
#
# Is queue empty?
#
if PQ.empty():
    print("queue is empty")
else:
    print("queue is non-empty")

Adding to the queue:
   value of thing added = 97.41633385074314
   value of thing added = 95.62631794718456
   value of thing added = 92.1731883728031
   value of thing added = 114.90113299782055
   value of thing added = 80.21795668158018
Number of things in the queue = 5
Printing queue contents without modifying it:
   114.90113299782055
   97.41633385074314
   92.1731883728031
   95.62631794718456
   80.21795668158018
Number of things in the queue = 5
queue is non-empty
   114.90113299782055
Number of things in queue = 4
   97.41633385074314
Number of things in queue = 3
   95.62631794718456
Number of things in queue = 2
   92.1731883728031
Number of things in queue = 1
   80.21795668158018
Number of things in queue = 0
queue is empty


## Here's a slightly more complicated example.

In [54]:
import queue as Q
import numpy as np

#
# Create a class of things to put in the queue.
#
class thing:
    __slots__=("v1","v2","v3")
    def __init__(self,v1,v2,v3):
        self.v1=v1
        self.v2=v2
        self.v3=v3
    def pcalc(self):
        return(self.v1+self.v2*self.v3)
    def __lt__(self,other):
        scalc=self.pcalc()
        ocalc=other.pcalc()
        if scalc<=ocalc:
            return(True)
        return(False)
    def __str__(self):
        return("   "+str(self.v1)+"  "+str(self.v2)+"  "+str(self.v3)+"  "+str(self.pcalc()))
    
#
# Create an instance of a priority queue
#
PQ=Q.PriorityQueue()
#
# Add some things to the queue 
#
print("Adding to the queue:")
for i in range(5):
    v1=np.random.normal(100,10,1)[0]
    v2=np.random.normal(100,10,1)[0]
    v3=np.random.normal(100,10,1)[0]
    t=thing(v1,v2,v3)
    PQ.put(t)
    print("   value of thing added = " + str(t.pcalc()))
print("Number of things in the queue = " + str(PQ.qsize()))
#
# Print the elements of the queue.
# This doesn't modify contents of the queue.
#
n=PQ.qsize()
print("Printing queue contents without modifying it:")
for i in range(n):
    print(PQ.queue[i])
print("Number of things in the queue = " + str(PQ.qsize()))
#
# Is queue empty?
#
if PQ.empty():
    print("queue is empty")
else:
    print("queue is non-empty")
#
# Get the elements one at a time.
#
while PQ.qsize():
    v=PQ.get()
    print(v)
    print("Number of things in queue = " + str(PQ.qsize()))
#
# Is queue empty?
#
if PQ.empty():
    print("queue is empty")
else:
    print("queue is non-empty")

Adding to the queue:
   value of thing added = 9271.63047345888
   value of thing added = 8452.646356395035
   value of thing added = 8447.940528232997
   value of thing added = 9190.41589953632
   value of thing added = 10186.276453269636
Number of things in the queue = 5
Printing queue contents without modifying it:
   94.3787390659608  94.36533909779365  88.5236239177818  8447.940528232997
   121.35868688506741  99.4424481215632  91.19905416613238  9190.41589953632
   78.23196973187652  87.24839356891786  95.9835940136614  8452.646356395035
   107.33412758966547  94.33546319867074  97.14582443475346  9271.63047345888
   95.34596773278612  97.86475453505378  103.1109773225091  10186.276453269636
Number of things in the queue = 5
queue is non-empty
   94.3787390659608  94.36533909779365  88.5236239177818  8447.940528232997
Number of things in queue = 4
   78.23196973187652  87.24839356891786  95.9835940136614  8452.646356395035
Number of things in queue = 3
   121.35868688506741  99.4