In [1]:
import numpy as np

In [6]:
x = [1,2,3,4,5]

In [7]:
type(x)

list

In [8]:
y = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]

In [10]:
y[0]

[1, 2, 3, 4, 5]

In [11]:
y

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

In [12]:
y[1]

[6, 7, 8, 9, 10]

In [15]:
y[2][0]

11

In [16]:
print(y)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


In [17]:
x

[1, 2, 3, 4, 5]

In [19]:
y_array = np.array(y)

In [21]:
type(y_array)

numpy.ndarray

In [24]:
y_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
y_array.shape

(3, 5)

In [28]:
y_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [29]:
y_array + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
y_array - 10

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5]])

In [31]:
y_array/10

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5]])

In [32]:
y_array2 = y_array*1.5

In [34]:
y_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
y_array2

array([[ 1.5,  3. ,  4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. , 13.5, 15. ],
       [16.5, 18. , 19.5, 21. , 22.5]])

In [35]:
y_array + y_array2

array([[ 2.5,  5. ,  7.5, 10. , 12.5],
       [15. , 17.5, 20. , 22.5, 25. ],
       [27.5, 30. , 32.5, 35. , 37.5]])

In [36]:
y_array - y_array2

array([[-0.5, -1. , -1.5, -2. , -2.5],
       [-3. , -3.5, -4. , -4.5, -5. ],
       [-5.5, -6. , -6.5, -7. , -7.5]])

In [37]:
y_array*y_array2

array([[  1.5,   6. ,  13.5,  24. ,  37.5],
       [ 54. ,  73.5,  96. , 121.5, 150. ],
       [181.5, 216. , 253.5, 294. , 337.5]])

In [38]:
y_array@y_array2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)

In [39]:
y_array.shape

(3, 5)

In [40]:
y_array2.shape

(3, 5)

In [42]:
x_array = np.array([[1,2,3],[4,5,6]])
x_array

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
xx_array = np.array([[1,2,3],[4,5,6]])
xx_array

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
x_array*xx_array

array([[ 1,  4,  9],
       [16, 25, 36]])

In [47]:
x_array

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
xx_array

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
x_array.shape

(2, 3)

In [52]:
y_array.shape

(3, 5)

In [54]:
x_array@y_array # matrix multiplication

array([[ 46,  52,  58,  64,  70],
       [100, 115, 130, 145, 160]])

In [56]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [57]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [61]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [66]:
np.random.randn(50)

array([-1.53222466, -0.59976843, -0.19325997,  0.69676809, -0.63107189,
       -1.17762756,  1.28938796,  0.06048446,  0.17018511,  0.54604199,
       -0.10647454,  1.78000795, -2.11097835,  1.03374722, -1.69765905,
       -1.13739886,  0.44833967, -0.28463073,  0.52354042, -0.80222784,
        0.78467553,  1.14887682,  0.31265091, -0.62107325, -1.33211927,
        1.58795085, -0.19638608,  0.19547943, -0.0167516 ,  0.52577439,
        0.85859495,  0.7706411 ,  1.47046454, -0.4830899 ,  0.24419706,
       -0.67509307,  0.45231324, -0.54531983, -1.80932244,  0.52666835,
        0.38139165, -0.42371199,  0.533304  ,  0.21167952, -0.14747447,
       -1.08017297, -0.2236436 , -0.1499624 ,  0.84572546, -0.31757776])

In [68]:
np.random.randn(10)

array([-0.01595763, -0.7457879 ,  0.15539099,  0.12711661,  1.03291887,
       -0.88106261, -0.78620989, -2.6236253 ,  1.44876503, -1.64098743])

In [71]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [72]:
np.arange(10,50,15)

array([10, 25, 40])

In [74]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [91]:
np.linspace(1,10,10,dtype='int32')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [76]:
6.44444444 - 11.88888889

-5.444444450000001

In [88]:
type(1.)

float

In [98]:
np.linspace(4294967300,42949672960,10,dtype='int64')

array([ 4294967300,  8589934595, 12884901891, 17179869186, 21474836482,
       25769803777, 30064771073, 34359738368, 38654705664, 42949672960],
      dtype=int64)

In [92]:
2**32

4294967296

In [104]:
np.random.rand(3,3)

array([[0.55391281, 0.82686232, 0.39607962],
       [0.69682364, 0.81365745, 0.43877624],
       [0.54552147, 0.15255192, 0.23316395]])

In [110]:
x = np.random.rand(3,3,1)

In [112]:
x[0]

array([[0.25632097],
       [0.02132455],
       [0.78794919]])

In [113]:
x

array([[[0.25632097],
        [0.02132455],
        [0.78794919]],

       [[0.93101123],
        [0.25020372],
        [0.16913074]],

       [[0.82880156],
        [0.59483905],
        [0.73056535]]])

In [115]:
np.random.rand(3,3,1)

array([[[0.68863986],
        [0.36065598],
        [0.99664757]],

       [[0.38807486],
        [0.86792104],
        [0.5598757 ]],

       [[0.17260943],
        [0.66904588],
        [0.0679712 ]]])

In [119]:
np.random.rand(3,3,1)

array([[[0.17494328],
        [0.36669824],
        [0.35517122]],

       [[0.85955722],
        [0.87715314],
        [0.20612063]],

       [[0.91815923],
        [0.97076629],
        [0.37532507]]])

In [124]:
np.random.randint(1,500)

477

In [125]:
np.random.randint(1,100,10)

array([17, 16, 40,  4, 50, 10, 53, 10, 76, 35])

In [126]:
x_array

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
x_array.shape

(2, 3)

In [131]:
x_array

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
x_array.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [133]:
x_array.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [134]:
x_array

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
np.zeros_like(x_array)

array([[0, 0, 0],
       [0, 0, 0]])

In [136]:
np.ones_like(x_array)

array([[1, 1, 1],
       [1, 1, 1]])

In [137]:
x_array

array([[1, 2, 3],
       [4, 5, 6]])

In [164]:
y_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [139]:
x_array = np.random.rand(3,3)

In [140]:
x_array

array([[0.91416731, 0.20251212, 0.79497269],
       [0.4201652 , 0.49313639, 0.91979315],
       [0.79428925, 0.82436549, 0.06144091]])

In [141]:
x_array.max()

0.9197931500882321

In [142]:
x_array.min()

0.06144091008286945

In [143]:
x_array.argmin()

8

In [147]:
x_array.argmax()

5

In [148]:
x_array.shape

(3, 3)

In [152]:
x_array

array([[0.91416731, 0.20251212, 0.79497269],
       [0.4201652 , 0.49313639, 0.91979315],
       [0.79428925, 0.82436549, 0.06144091]])

In [153]:
x_array[0]

array([0.91416731, 0.20251212, 0.79497269])

In [154]:
x_array[1]

array([0.4201652 , 0.49313639, 0.91979315])

In [155]:
x_array[2]

array([0.79428925, 0.82436549, 0.06144091])

In [156]:
x_array[2][1]

0.8243654924689747

In [158]:
x_array.dtype

dtype('float64')

In [159]:
type(x_array)

numpy.ndarray

In [161]:
x_array.reshape(9,1)

array([[0.91416731],
       [0.20251212],
       [0.79497269],
       [0.4201652 ],
       [0.49313639],
       [0.91979315],
       [0.79428925],
       [0.82436549],
       [0.06144091]])

In [162]:
x_array.reshape(1,9)

array([[0.91416731, 0.20251212, 0.79497269, 0.4201652 , 0.49313639,
        0.91979315, 0.79428925, 0.82436549, 0.06144091]])

In [163]:
x_array.reshape(9,-1)

array([[0.91416731],
       [0.20251212],
       [0.79497269],
       [0.4201652 ],
       [0.49313639],
       [0.91979315],
       [0.79428925],
       [0.82436549],
       [0.06144091]])

In [165]:
y_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [166]:
y_array.shape

(3, 5)

In [171]:
y_array = y_array.reshape(5,-1)

In [172]:
y_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [175]:
y_array.reshape(15,-1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [179]:
x_array

array([[0.91416731, 0.20251212, 0.79497269],
       [0.4201652 , 0.49313639, 0.91979315],
       [0.79428925, 0.82436549, 0.06144091]])

In [180]:
x_array[0:2,]

array([[0.91416731, 0.20251212, 0.79497269],
       [0.4201652 , 0.49313639, 0.91979315]])

In [182]:
x_array[0:2,0:2]

array([[0.91416731, 0.20251212],
       [0.4201652 , 0.49313639]])

In [187]:
x_array[x_array>0.5]

array([0.91416731, 0.79497269, 0.91979315, 0.79428925, 0.82436549])

In [191]:
x_array

array([[0.91416731, 0.20251212, 0.79497269],
       [0.4201652 , 0.49313639, 0.91979315],
       [0.79428925, 0.82436549, 0.06144091]])

In [190]:
x_array[[1,2]]

array([[0.4201652 , 0.49313639, 0.91979315],
       [0.79428925, 0.82436549, 0.06144091]])

In [193]:
x_array[[0,1]]

array([[0.91416731, 0.20251212, 0.79497269],
       [0.4201652 , 0.49313639, 0.91979315]])

In [194]:
x_array[:2,]

array([[0.91416731, 0.20251212, 0.79497269],
       [0.4201652 , 0.49313639, 0.91979315]])

In [195]:
x_array

array([[0.91416731, 0.20251212, 0.79497269],
       [0.4201652 , 0.49313639, 0.91979315],
       [0.79428925, 0.82436549, 0.06144091]])

In [206]:
x_array = np.linspace(1,10,10)

In [207]:
x_array = x_array.reshape(2,5)
x_array

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [208]:
x_array.mean()

5.5

In [209]:
x_array.mean(axis=0)

array([3.5, 4.5, 5.5, 6.5, 7.5])

In [210]:
x_array.mean(axis=1)

array([3., 8.])

In [211]:
x_array.std()

2.8722813232690143

In [214]:
np.sqrt(x_array)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766]])

In [215]:
np.exp(x_array)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04]])

In [222]:
float('NaN')

nan

In [223]:
float('nan')

nan

In [224]:
float('inf')

inf

In [228]:
float('infinity')

inf

In [229]:
# Q1 , hint: np.where() less than 7 and more than 7

In [5]:
x_array = np.random.rand(3,3)

In [6]:
x_array

array([[0.47094805, 0.40184898, 0.90262696],
       [0.72773159, 0.71789294, 0.4918003 ],
       [0.72012978, 0.90625908, 0.67947197]])

In [11]:
np.where(x_array>0.6,True,False)

array([[False, False,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [20]:
a = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 6]])

In [21]:
a

array([[0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [28]:
np.where(a>2,a,-1)

array([[-1, -1, -1],
       [-1, -1,  4],
       [-1,  3,  6]])

In [22]:
np.where(a>2)

(array([1, 2, 2], dtype=int64), array([2, 1, 2], dtype=int64))

In [23]:
a

array([[0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [24]:
a[1,2]

4

In [25]:
a[2,1]

3

In [26]:
a[2,2]

6

In [33]:
np.where(a>2,True,False)

array([[False, False, False],
       [False, False,  True],
       [False,  True,  True]])

In [34]:
a[np.where(a>2,True,False)]

array([4, 3, 6])

In [32]:
a

array([[0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])