In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("LeastCostPath.ipynb")

You will need to execute the following cell to use this notebook. 

**Important Notes:**

- when doing Otter assignments please do not include extraneous materials, including code, print statements. 

- if you do need to write extra code for testing purposes, please do it in another notebook and copy only the needed code to answer the problems into the notebook you hand in.

- don't forget to execute your cells in order and save your work before turning yout work in.

- this assignment assumes you are working in an environment in which the **sympy** package has been installed.

- this assignment uses the json package **which does not require installation.**

- before beginning this assignment, you should read the pdf entitled **Least Cost Path in a Rectangular Grid** and your answers below should make use of pseudo-code provided there.

- all *tests* in this notebook are *hidden* unless indicated otherwise. So no feedback becomes available until the notebook is graded.


In [2]:
import numpy as np
import pandas as pd
from sympy.utilities.iterables import multiset_permutations
import otter
grader = otter.Notebook()

## Sympy 
We will use the sympy package to since it allows us to generate all possible permutations of the elements of a list. The list can consist of identical values, hence the term *multiset*. As you are all aware, the number of permutations of aaabb is Binomal(5,3) = 10.

In [3]:
perms=multiset_permutations(["a","a","a","b","b"])
for p in perms:
    print(p)

['a', 'a', 'a', 'b', 'b']
['a', 'a', 'b', 'a', 'b']
['a', 'a', 'b', 'b', 'a']
['a', 'b', 'a', 'a', 'b']
['a', 'b', 'a', 'b', 'a']
['a', 'b', 'b', 'a', 'a']
['b', 'a', 'a', 'a', 'b']
['b', 'a', 'a', 'b', 'a']
['b', 'a', 'b', 'a', 'a']
['b', 'b', 'a', 'a', 'a']


## Saving and Loading Numpy Arrays

H and V arrays for sample problems have been created using code in the ProblemFiles.ipynb file. You can see there that these arrays are created using a numpy random number generator. The numpy **save** command is used to save the files. Whatever file name is used as an argument, by default the suffix *".npy"*  is appended to the file name, and the file is saved in a format that can be rea using **in any platform** using the numpy **load** command.

In the code below several numpy arrays are loaded. **You should not modify these arrays anywhere in the notebook.**

In [4]:
H1=np.load("H1.npy")
V1=np.load("V1.npy")
print(H1)
print("\n")
print(V1)
H2=np.load("H2.npy")
V2=np.load("V2.npy")
H3=np.load("H3.npy")
V3=np.load("V3.npy")
H4=np.load("H4.npy")
V4=np.load("V4.npy")
H5=np.load("H5.npy")
V5=np.load("V5.npy")

[[0.54340494 0.27836939 0.42451759]
 [0.84477613 0.00471886 0.12156912]
 [0.67074908 0.82585276 0.13670659]
 [0.57509333 0.89132195 0.20920212]
 [0.18532822 0.10837689 0.21969749]]


[[0.97862378 0.81168315 0.17194101 0.81622475]
 [0.27407375 0.43170418 0.94002982 0.81764938]
 [0.33611195 0.17541045 0.37283205 0.00568851]
 [0.25242635 0.79566251 0.01525497 0.59884338]]


Write a function called **GetIndicesOfPath** that takes as input a **path**, which is list of individual characters from among {"H","V"} and outputs a list of 2-tuples giving the pairs of indices $(I,J)$ corresponding to positions in a matrix starting from $(0,0)$ and ending with $(m,n)$ where $m$ is the number of V's in the path, and $n$ is the number of H's in the path.

So for example, the path ['H','H','V','V','H'] should give as output the *list*
[(0,0),(0,1),(0,2),(1,2),(2,2),(2,3)]

<!--
BEGIN QUESTION
name: q1
manual: false
points: 1
-->

In [5]:
def GetIndicesOfPath(path):
    finalPath = [(0,0)]
    x, y = 0, 0
    for curC in path:
        if curC == 'H':
            y += 1
            finalPath.append((x,y))
        elif curC == 'V':
            x += 1
            finalPath.append((x,y))
    return finalPath
#
# Do not modify the following lines
#
path=['H','H','V','V','H']
print(GetIndicesOfPath(path))

[(0, 0), (0, 1), (0, 2), (1, 2), (2, 2), (2, 3)]


In [6]:
grader.check("q1")

q1 results: All test cases passed!

Write a function called **PathCost** that takes as inputs the following:

- two positive integers **m** and **n**, giving grid dimenssions, 
- a numpy array **H** ($m \times (n+1)$) giving, in position $(i,j)$ the cost of a horizontal move from $(i,j)$ to $(i+1,j),$ and
- a numpy array **V** ($m+1 \times n)$ giving, in postion $(i,j)$ the cost of a vertical move from $(i,j)$ to $(i,j+1)$
- a **path**, which is a list of characters of size $m+n$ consisting of $m$ H's and $n$ V's. 

and as output the cost of moving from $(0,0)$ to $(m,n)$ defined by the horizontal and vertical moves in path.

<!--
BEGIN QUESTION
name: q2
manual: false
points: 2
-->

In [7]:
def PathCost(m,n,H,V,path): 
    cost = 0
    cnt = 0
    row, col = 0, 0
    for curIndex in range(len(path)):
        if path[curIndex] == 'H':
            cost += H[row][col]
            cnt += 1
            col += 1
        elif path[curIndex] == 'V':
            cost += V[row][col]
            cnt += 1
            row += 1
    return(cost) 
#
# Do not modify the following lines
#
m=4
n=3
cost=PathCost(4,3,H1,V1,["V" for i in range(m)]+["H" for i in range(n)])
print(cost)

2.3546384379541303


In [8]:
grader.check("q2")

q2 results: All test cases passed!

Write a function called **LeastCostPathBruteForce** that takes as input

- two positive integers **m** and **n**, giving grid dimensions, 
- a numpy array **H** ($m \times (n+1)$) giving, in position $(i,j)$ the cost of a horizontal move from $(i,j)$ to $(i,j+1),$ and
- a numpy array **V** ($m+1 \times n)$ giving, in postion $(i,j)$ the cost of a vertical move from $(i,j)$ to $(i+1,j)$

and as output gives a 2-tuple containing (in the following order):

- the **cost** (a number) of a least cost path from $(0,0)$ to $(m,n)$ **rounded to 3 decimal places,** and 
- an optimal path, which should be a list of 2-tuples [(0,0),....,(m,n)] giving nodes visited along an optimal path *in order*.

Your function should solve the problem using the **brute-force** approach of iterating over all possible paths.

It is always a good idea to test your code problems where a brute-force solution can be found. This code will not be useful practically for large values of $m$ and $n$ but you **can** use it for testing purposes. 

It would be wise to test your code on some small examples in a **different notebook**.

<!--
BEGIN QUESTION
name: q3
manual: false
points: 4
-->

In [9]:
def LeastCostPathBruteForce(m,n,H,V):
    firstPath = True
    L = ["V" for i in range(m)] + ["H" for i in range(n)]
    allpaths = multiset_permutations(L)
    mincost = 0
    minpath = ''
    for curPath in allpaths:
        cost = PathCost(m, n, H, V, curPath)
        if firstPath:
            mincost = cost
            firstPath = False
        else:
            if mincost > cost:
                mincost = cost
                minpath = curPath
    mincost = format(mincost, '.3f')
    path = GetIndicesOfPath(minpath)
    return ((mincost,path))
#
# Do not modify the following lines.
#
mincost1=LeastCostPathBruteForce(4,3,H1,V1)
mincost2=LeastCostPathBruteForce(5,8,H2,V2)
print(mincost1[0])
print(mincost1[1])
print(mincost2[0])
print(mincost2[1])

2.355
[(0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (4, 1), (4, 2), (4, 3)]
3.937
[(0, 0), (0, 1), (1, 1), (1, 2), (2, 2), (3, 2), (3, 3), (3, 4), (4, 4), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8)]


In [10]:
grader.check("q3")

q3 results: All test cases passed!

Write code to compute the same output, but using dynamic programming as described in the *LeastCostPathInRectangularGrid.pdf* document. Call this function **LeastCostPathDynamicProgramming**.

**Make sure** you round your least cost solution to 3 decimal places.

Before doing the hidden tests, you should test your code in **a different notebook** on random cases when m and n are small enough so that the brute-force method can be applied and you should get the same answers using the two methods provided that there is no possibility of multiple optimal paths. (This will have a **very small probability** if you take V and H to be random with uniformly distributed entries.)

<!--
BEGIN QUESTION
name: q4
manual: false
points: 5
-->

In [11]:
def LeastCostPathDynamicProgramming(m,n,H,V):
    dp = [[0 for col in range(n + 1)] for row in range(m + 1)]
    dPath = [['' for col in range(n + 1)] for row in range(m + 1)]
    
    for row in range(m):
        dp[row + 1][0] = dp[row][0] + V[row][0]
        dPath[row + 1][0] = 'V'
        
    for col in range(n):
        dp[0][col + 1] = dp[0][col] + H[0][col]
        dPath[0][col + 1] = 'H'
        
    for row in range(1, m + 1):
        for col in range(1, n + 1):
            if dp[row][col - 1] + H[row][col - 1] < dp[row - 1][col] + V[row - 1][col]:
                dp[row][col] = dp[row][col - 1] + H[row][col - 1]
                dPath[row][col] = 'H'
            else:
                dp[row][col] = dp[row - 1][col] + V[row - 1][col]
                dPath[row][col] = 'V'
    
    OptimalPathNodes = [(m,n)]
    endX = m
    endY = n
    while len(OptimalPathNodes) < m + n + 1:
        if dPath[endX][endY] == 'V':
            endX -= 1
        else:
            endY -= 1
        OptimalPathNodes.append((endX, endY))
    
    OptimalPathNodesResults = []
    lengthL = len(OptimalPathNodes) - 1
    while lengthL >= 0:
        OptimalPathNodesResults.append(OptimalPathNodes[lengthL])
        lengthL -= 1
    
    mincost = format(dp[m][n], '.3f')
    return mincost, OptimalPathNodesResults
            
#
# Do not modify the following lines.
#
mincost11=LeastCostPathDynamicProgramming(4,3,H1,V1)
mincost12=LeastCostPathBruteForce(4,3,H1,V1)
print(mincost11)
print(mincost12)
mincost21=LeastCostPathDynamicProgramming(5,8,H2,V2)
mincost22=LeastCostPathBruteForce(5,8,H2,V2)
print(mincost21)
print(mincost22)

('2.355', [(0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (4, 1), (4, 2), (4, 3)])
('2.355', [(0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (4, 1), (4, 2), (4, 3)])
('3.937', [(0, 0), (0, 1), (1, 1), (1, 2), (2, 2), (3, 2), (3, 3), (3, 4), (4, 4), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8)])
('3.937', [(0, 0), (0, 1), (1, 1), (1, 2), (2, 2), (3, 2), (3, 3), (3, 4), (4, 4), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8)])


In [12]:
grader.check("q4")

q4 results: All test cases passed!

**Final Instructions:**
1) save your notebook befor submitting it in Canvas
2) do **not** zip your notebook 
3) do **not** change the name of your notebook


---

To double-check your work, the cell below will rerun all of the autograder tests.

In [ ]:
grader.check_all()