In [108]:
import pandas as pd

In [109]:
df_train = pd.read_csv('GOOG_train10.csv')
df_test = pd.read_csv('GOOG_test10.csv')

In [110]:
df_train

Date         Open         High          Low        Close  \
0     2011-01-03   297.126312   301.664276   297.126312   301.046600   
1     2011-01-04   301.679230   301.958191   298.939514   299.935760   
2     2011-01-05   298.914581   304.025452   298.904633   303.397797   
3     2011-01-06   304.199799   308.060303   303.885956   305.604523   
4     2011-01-07   306.805023   307.970642   303.925812   307.069031   
...          ...          ...          ...          ...          ...   
2751  2021-12-07  2919.000000  2966.000000  2914.050049  2960.729980   
2752  2021-12-08  2966.629883  2983.129883  2944.000000  2974.409912   
2753  2021-12-09  2963.520020  2992.100098  2950.580078  2962.120117   
2754  2021-12-10  2982.000000  2988.000000  2947.149902  2973.500000   
2755  2021-12-13  2968.879883  2971.250000  2927.199951  2934.090088   

        Adj Close   Volume  
0      301.046600  4748131  
1      299.935760  3662677  
2      303.397797  5083583  
3      305.604523  4131026  
4      307.069031  4218152  
...           ...      ...  
2751  2960.729980  1162900  
2752  2974.409912   948200  
2753  2962.120117   929000  
2754  2973.500000  1081700  
2755  2934.090088  1205200  

[2756 rows x 7 columns]

In [111]:
df_test

Date         Open         High          Low        Close  \
0   2021-12-14  2895.399902  2908.840088  2844.850098  2899.409912   
1   2021-12-15  2887.320068  2950.344971  2854.110107  2947.370117   
2   2021-12-16  2961.540039  2971.030029  2881.850098  2896.770020   
3   2021-12-17  2854.290039  2889.201904  2835.760010  2856.060059   
4   2021-12-20  2813.592041  2852.209961  2805.000000  2848.030029   
5   2021-12-21  2863.000000  2893.841064  2834.699951  2884.409912   
6   2021-12-22  2882.000000  2946.060059  2879.260010  2938.979980   
7   2021-12-23  2941.790039  2971.451904  2939.017090  2942.850098   
8   2021-12-27  2949.270020  2968.530029  2945.000000  2961.280029   
9   2021-12-28  2967.489990  2967.489990  2918.709961  2928.959961   
10  2021-12-29  2928.590088  2943.675049  2910.090088  2930.090088   
11  2021-12-30  2929.000000  2941.250000  2915.169922  2920.050049   
12  2021-12-31  2910.879883  2927.300049  2893.550049  2893.590088   
13  2022-01-03  2889.510010  2911.000000  2870.050049  2901.489990   
14  2022-01-04  2911.010010  2932.199951  2876.322998  2888.330078   
15  2022-01-05  2883.620117  2885.959961  2750.469971  2753.070068   
16  2022-01-06  2749.949951  2793.719971  2735.270020  2751.020020   
17  2022-01-07  2758.100098  2765.094971  2715.780029  2740.090088   
18  2022-01-10  2701.979980  2772.800049  2662.810059  2771.479980   
19  2022-01-11  2763.610107  2806.590088  2736.270020  2800.350098   
20  2022-01-12  2831.090088  2856.284912  2822.239990  2832.959961   
21  2022-01-13  2836.810059  2863.709961  2778.280029  2782.620117   
22  2022-01-14  2750.000000  2824.010010  2750.000000  2795.729980   
23  2022-01-18  2732.000000  2747.830078  2712.340088  2725.810059   
24  2022-01-19  2738.770020  2767.989990  2710.000000  2713.040039   
25  2022-01-20  2730.280029  2758.239990  2662.889893  2670.129883   
26  2022-01-21  2660.239990  2695.209961  2600.020020  2601.840088   
27  2022-01-24  2520.550049  2615.570068  2492.839111  2607.439941   
28  2022-01-25  2568.709961  2586.770020  2527.560059  2534.709961   
29  2022-01-26  2611.850098  2656.149902  2543.070068  2584.800049   
30  2022-01-27  2627.219971  2652.198975  2578.899902  2582.419922   
31  2022-01-28  2600.000000  2667.409912  2573.889893  2665.790039   
32  2022-01-31  2683.959961  2716.870117  2645.479980  2713.969971   
33  2022-02-01  2756.699951  2764.000000  2691.364990  2757.570068   
34  2022-02-02  3037.270020  3042.000000  2911.149902  2960.729980   
35  2022-02-03  2905.899902  2982.354004  2844.100098  2853.010010   
36  2022-02-04  2860.340088  2890.705078  2796.350098  2860.320068   
37  2022-02-07  2874.179932  2876.929932  2773.979980  2778.760010   
38  2022-02-08  2779.824951  2796.741943  2737.459961  2784.260010   
39  2022-02-09  2816.995117  2843.510010  2807.540039  2829.060059   
40  2022-02-10  2790.000000  2828.620117  2761.000000  2772.050049   
41  2022-02-11  2775.000000  2785.665039  2665.770020  2682.600098   

      Adj Close   Volume  
0   2899.409912  1238900  
1   2947.370117  1364000  
2   2896.770020  1370000  
3   2856.060059  2162800  
4   2848.030029  1013200  
5   2884.409912   977400  
6   2938.979980   921900  
7   2942.850098   690900  
8   2961.280029   662800  
9   2928.959961   931200  
10  2930.090088   851100  
11  2920.050049   648900  
12  2893.590088   864900  
13  2901.489990  1260700  
14  2888.330078  1146400  
15  2753.070068  2482100  
16  2751.020020  1452500  
17  2740.090088   970100  
18  2771.479980  1704800  
19  2800.350098  1175100  
20  2832.959961  1182100  
21  2782.620117  1328300  
22  2795.729980  1190700  
23  2725.810059  1369100  
24  2713.040039  1039800  
25  2670.129883  1096500  
26  2601.840088  2096000  
27  2607.439941  2757400  
28  2534.709961  1800400  
29  2584.800049  1981500  
30  2582.419922  1512400  
31  2665.790039  1525900  
32  2713.969971  1702800  
33  2757.570068  2560200  
34  2960.729980  4487500  
35  2853.010010  2846500  


In [112]:
df_train = df_train.filter(['Close']).values
df_test = df_test.filter(['Close']).values

In [113]:
df_train_copy = df_train.copy()
df_test_copy = df_test.copy()

In [114]:
df_train

array([[ 301.0466  ],
       [ 299.93576 ],
       [ 303.397797],
       ...,
       [2962.120117],
       [2973.5     ],
       [2934.090088]])

In [115]:
df_test

array([[2899.409912],
       [2947.370117],
       [2896.77002 ],
       [2856.060059],
       [2848.030029],
       [2884.409912],
       [2938.97998 ],
       [2942.850098],
       [2961.280029],
       [2928.959961],
       [2930.090088],
       [2920.050049],
       [2893.590088],
       [2901.48999 ],
       [2888.330078],
       [2753.070068],
       [2751.02002 ],
       [2740.090088],
       [2771.47998 ],
       [2800.350098],
       [2832.959961],
       [2782.620117],
       [2795.72998 ],
       [2725.810059],
       [2713.040039],
       [2670.129883],
       [2601.840088],
       [2607.439941],
       [2534.709961],
       [2584.800049],
       [2582.419922],
       [2665.790039],
       [2713.969971],
       [2757.570068],
       [2960.72998 ],
       [2853.01001 ],
       [2860.320068],
       [2778.76001 ],
       [2784.26001 ],
       [2829.060059],
       [2772.050049],
       [2682.600098]])

In [116]:
# Scale the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,1))
df_train = scaler.fit_transform(df_train)

df_train

array([[0.02321884],
       [0.02281891],
       [0.02406531],
       ...,
       [0.98125745],
       [0.98535443],
       [0.97116609]])

In [117]:
df_test = scaler.fit_transform(df_test)

In [118]:
# Split the data into x_train and y_train data sets
x_train = []
y_train = []

for i in range(10, len(df_train)):
    x_train.append(df_train[i-10:i, 0])
    y_train.append(df_train_copy[i, 0])
    if i<= 11:
        print(x_train)
        print(y_train)
        print()

[array([0.02321884, 0.02281891, 0.02406531, 0.02485978, 0.02538703,
       0.0249871 , 0.02530991, 0.02546415, 0.02543187, 0.02677511])]
[318.620728]

[array([0.02321884, 0.02281891, 0.02406531, 0.02485978, 0.02538703,
       0.0249871 , 0.02530991, 0.02546415, 0.02543187, 0.02677511]), array([0.02281891, 0.02406531, 0.02485978, 0.02538703, 0.0249871 ,
       0.02530991, 0.02546415, 0.02543187, 0.02677511, 0.02954587])]
[318.620728, 314.69543500000003]



In [119]:
len(x_train)

2746

In [120]:
len(y_train)

2746

In [121]:
# Convert the x_train and y_train to numpy arrays 
import numpy as np
x_train, y_train = np.array(x_train), np.array(y_train)

# Reshape the data
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
# x_train.shape

In [122]:
x_train.shape

(2746, 10, 1)

In [123]:
x_train

array([[[0.02321884],
        [0.02281891],
        [0.02406531],
        ...,
        [0.02546415],
        [0.02543187],
        [0.02677511]],

       [[0.02281891],
        [0.02406531],
        [0.02485978],
        ...,
        [0.02543187],
        [0.02677511],
        [0.02954587]],

       [[0.02406531],
        [0.02485978],
        [0.02538703],
        ...,
        [0.02677511],
        [0.02954587],
        [0.02813268]],

       ...,

       [[0.9712597 ],
        [0.94309537],
        [0.96691423],
        ...,
        [0.95022729],
        [0.98075697],
        [0.98568201]],

       [[0.94309537],
        [0.96691423],
        [0.9405464 ],
        ...,
        [0.98075697],
        [0.98568201],
        [0.98125745]],

       [[0.96691423],
        [0.9405464 ],
        [0.9345413 ],
        ...,
        [0.98568201],
        [0.98125745],
        [0.98535443]]])

In [124]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

# Build the LSTM model
model = Sequential()
model.add(LSTM(128, return_sequences=True, input_shape= (x_train.shape[1], 1)))
model.add(LSTM(64, return_sequences=False))
model.add(Dense(25))
model.add(Dense(1))

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(x_train, y_train, batch_size=1, epochs=1)

2746/2746 [==============================] - 39s 12ms/step - loss: 316429.5312


In [125]:
# Split the data into x_train and y_train data sets
x_test = []
y_test = []

for i in range(10, len(df_test)):
    x_test.append(df_test[i-10:i, 0])
    y_test.append(df_test_copy[i, 0])
    if i<= 11:
        print(x_test)
        print(y_test)
        print()

[array([0.85495908, 0.96739126, 0.84877043, 0.75333485, 0.7345102 ,
       0.81979486, 0.94772242, 0.95679507, 1.        , 0.92423269])]
[2930.090088]

[array([0.85495908, 0.96739126, 0.84877043, 0.75333485, 0.7345102 ,
       0.81979486, 0.94772242, 0.95679507, 1.        , 0.92423269]), array([0.96739126, 0.84877043, 0.75333485, 0.7345102 , 0.81979486,
       0.94772242, 0.95679507, 1.        , 0.92423269, 0.92688202])]
[2930.090088, 2920.050049]



In [126]:
# Convert the x_train and y_train to numpy arrays 
import numpy as np
x_test, y_test = np.array(x_test), np.array(y_test)

# Reshape the data
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))
# x_train.shape

In [127]:
# Get the models predicted price values 
predictions = model.predict(x_test)

1/1 [==============================] - 2s 2s/step


In [128]:
# predictions = scaler.inverse_transform(predictions)

# Get the root mean squared error (RMSE)
rmse = np.sqrt(np.mean(((predictions - y_test) ** 2)))
rmse

1093.8051959380387

In [129]:
pd.DataFrame({'predictions':predictions[:,0].tolist(),'Actual':y_test})

predictions       Actual
0   2032.897583  2930.090088
1   2032.788452  2920.050049
2   2032.434814  2893.590088
3   2032.652222  2901.489990
4   2033.069092  2888.330078
5   2033.339478  2753.070068
6   2033.433105  2751.020020
7   2033.404541  2740.090088
8   2033.328491  2771.479980
9   2033.101196  2800.350098
10  2032.720947  2832.959961
11  2031.288208  2782.620117
12  2024.439941  2795.729980
13  1996.896973  2725.810059
14  1916.787598  2713.040039
15  1838.155151  2670.129883
16  1859.474487  2601.840088
17  1860.642212  2607.439941
18  1836.360718  2534.709961
19  1721.458496  2584.800049
20  1543.944214  2582.419922
21  1354.855957  2665.790039
22  1210.615723  2713.969971
23  1031.652344  2757.570068
24   923.584045  2960.729980
25   910.988586  2853.010010
26  1032.182983  2860.320068
27  1266.926636  2778.760010
28  1484.678711  2784.260010
29  1678.592773  2829.060059
30  1848.664307  2772.050049
31  1975.264160  2682.600098