In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("Nim.ipynb")

# You will need to execute the following cell to use this notebook. 

# Note - all *tests* in this notebook are *hidden* unless indicated otherwise.

In [2]:
import numpy as np
import otter
grader = otter.Notebook()

Nim (https://en.wikipedia.org/wiki/Nim) is a game involving two players. 
At the start of the game, a  finite number of piles of stones is laid down. 
Then the players take turns removing stones according to the following rules:

- a player picks a pile of stones to remove from
- the player removes any positive number of stones from that pile (including the possibility of removing the entire pile)

The winner is the player who is able to remove stones for the last time. In other words, if a player empties the last empty pile they become the winner.

In 1902, a mathematician named Charles Bouton

(https://en.wikipedia.org/wiki/Charles_L._Bouton) 

published a paper with the winning strategy for the game. In particular, he found a simple algorithm to determine from the numbers of stones in the piles presented to the player who goes first whether, assuming both players play optimally, who should win the game, and he describes the winning strategy for the player who should win.

In doing this, he launched a mathematical field called *combinatorial game theory.*

In this assignment, we will go through the steps of writing some code that 
takes as input the numbers of stones in each pile on a given players turn, and tells whether the player should win or lose and code that describes what the winning player should do in order to play optimally.  

**Some Numpy:**

In an exercise below, we'll do a computation for $m$ trials. In each trial we will produce a list $L$ of $n$ values, so the results can be loaded into a list of lists.

So we will produce a list of lists which we can call $L$ and the values form what we usually think of as an $m \times n$ matrix:

$$
\left[\begin{array}{cccc}
L[0][0] &  L[0][1] &   \cdots & L[0][n-1]\\
L[1][0] &  L[1][1] & \cdots    & L[1][n-1]\\
\vdots & \vdots & \vdots & \vdots \\
\vdots & \vdots & \vdots & \vdots \\
L[m-1][0] & L[m-1][1] &  \cdots & L[m-1][n-1]\\
\end{array}\right]
$$

Then we want to summarize the columns in this matrix by computing some *statistic* of interest (e.g. the mean, the median, the standard deviation, percentiles) for every column to give a one-dimensional array or list of values of size $n$

To make things easier, we can convert our list of lists to a 2-d numpy array, then make use a function in numpy called *apply_along*. 

Here is a small example.

In [3]:
# start with a list
mylist=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
print(mylist)
print("\n")

# convert to a numpy array
mynparray=np.array(mylist)
print(mynparray)
print("\n")

# apply the mean function along axis=0 i.e. 
# sweep across horizontally and compute something along every column
result=np.apply_along_axis(np.mean,axis=0,arr=mynparray)
print(result)
print("\n")

# apply the mean function along axis=1 i.e. 
# sweep down vertically and compute something along every row
result=np.apply_along_axis(np.mean,axis=1,arr=mynparray)
print(result)
print("\n")

# we can also convert back to a list if desired
resultlist=list(result)
print(resultlist)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[5. 6. 7. 8.]


[ 2.5  6.5 10.5]


[2.5, 6.5, 10.5]


Numpy supported statistics include mean(), median(), quantile() (e.g. 75th percentile), std() (standard deviation) and sum().

Importantly, you can also use the *apply_along_axis* with a user-defined function.

Write a function called **binary_digits_of_integer** that takes as input a <u> nonnegative </u> integer $n$ and outputs a list of its binary digits.  The output list should be as short in length as possible. (If the input is the number 0, the output should be [0].) The digits should be ordered from highest powers of 2 to the lowest, so the last entry should be what is in the 1's place, the second to last entry, (if there is one) should be what is in the 2's place, the third to last (if there is one) shoud be what is in the 4ths place. 

For example, the decimal number 23 in binary is 
$$
16+4+2+1 = 1\times 2^4 + 0 \times 2^3 + 1\times 2^2 + 1 \times 2^1 + 1\times 2^0
$$

so its binary representation is 10111. Thus, the value of binary_digits_of_integer(23) should be the list [1,0,1,1,1].

The decimal number 37 is $32+4+1$, and expressed in binary this is 100101.
so binary_digits_of_integer(37) should be the list [1,0,0,1,0,1] and binary_digits_of_integer(1) should be [1].

You can use any method you like to code this function, but here are a couple of tools you might want to make use of. 

1) In Python we use m%n to determine remainder when the integer $m$ is divided by the positive integer $n.$

2) In Python, lists have a *reverse()* method that reverses the order of its elements.

You should test your function on the examples below and make sure your function works properly.

<!--
BEGIN QUESTION
name: q1
manual: false
points: 2
-->

In [4]:
def binary_digits_of_integer(n):
    binary = "{0:b}".format(int(n))
    return list(binary)
#
# Do not modify the following lines.
#
print(binary_digits_of_integer(0))
print(binary_digits_of_integer(1))
print(binary_digits_of_integer(2))
print(binary_digits_of_integer(29))
print(binary_digits_of_integer(61))

['0']
['1']
['1', '0']
['1', '1', '1', '0', '1']
['1', '1', '1', '1', '0', '1']


In [5]:
grader.check("q1")

q1 results: All test cases passed!

Create a function that takes as input a *list* of integers, and which outputs a list of the binary digit lists obtained from your *binary_digits_of_integer* function. The order in which the binary digit lists appear should match the order of the list of input integers.

Call this function, **binary_digits_for_list_of_integers**. For example, if the input to your function is [14,3,8,5] the output should be [[1,1,1,0],[1,1],[1,0,0,0],[1,0,1]].


<!--
BEGIN QUESTION
name: q2
manual: false
points: 1
-->

In [6]:
def binary_digits_for_list_of_integers(L): 
    return [binary_digits_of_integer(n) for n in L]
#
# Do not modify the following lines.
#
print(binary_digits_for_list_of_integers([5,6,7,8,9]))
print(binary_digits_for_list_of_integers([7,6,5,4,3,2,1,0]))

[['1', '0', '1'], ['1', '1', '0'], ['1', '1', '1'], ['1', '0', '0', '0'], ['1', '0', '0', '1']]
[['1', '1', '1'], ['1', '1', '0'], ['1', '0', '1'], ['1', '0', '0'], ['1', '1'], ['1', '0'], ['1'], ['0']]


In [7]:
grader.check("q2")

q2 results: All test cases passed!

Write another function that is like *binary_digits_for_list_of_integers* but for this one

- make it so that all of the lists of binary digits for all of the numbers in the list **have the same length,**

and 

- instead of outputting a list of lists, output a **2-d numpy array.**

So you might have to *pad* some of the lists with *initial* zeros to make the lengths equal. Call this function **array_of_binary_digits_for_list_of_integers**. The resulting lengths of binary digits should be as small as possible (i.e. the maximum number of binary digits should be the number of binary digits for the largest integer in the input list).

So for example, array_of_binary_digits_for_list_of_integers([14,3,8,5]) should give as output the numpy array

[[1,1,1,0],[0,0,1,1],[1,0,0,0],[0,1,0,1]].


<!--
BEGIN QUESTION
name: q3
manual: false
points: 2
-->

In [8]:
import numpy as np
def array_of_binary_digits_for_list_of_integers(L):
    list_BinaryNums = binary_digits_for_list_of_integers(L)
    max_length = max([len(i) for i in list_BinaryNums])
    list_BinaryNums = [[0]*(max_length-len(i))+i if len(i)<max_length else i for i in list_BinaryNums]
    return np.array(list_BinaryNums)
    
#
# Do not modify the following lines
#
print(array_of_binary_digits_for_list_of_integers([0,4,8,5,0]))
print(array_of_binary_digits_for_list_of_integers([16,2,3,5]))
print(array_of_binary_digits_for_list_of_integers([1,2,129]))

[['0' '0' '0' '0']
 ['0' '1' '0' '0']
 ['1' '0' '0' '0']
 ['0' '1' '0' '1']
 ['0' '0' '0' '0']]
[['1' '0' '0' '0' '0']
 ['0' '0' '0' '1' '0']
 ['0' '0' '0' '1' '1']
 ['0' '0' '1' '0' '1']]
[['0' '0' '0' '0' '0' '0' '0' '1']
 ['0' '0' '0' '0' '0' '0' '1' '0']
 ['1' '0' '0' '0' '0' '0' '0' '1']]


In [9]:
grader.check("q3")

q3 results: All test cases passed!

The parity of a list (or 1-d array) of 0's and 1's is defined to be 0 if the number of 1's in the list is even, and 1 if the number of 1's in the list is odd.

Write a function that determines the parity of a list or 1-d numpy array of 0's and 1's. Your function should work whether the input is a list or numpy array of ints, all of which are 0 or 1, and your function needn't work for lists of arrays of floats. 

Call your function **parity**.

<!--
BEGIN QUESTION
name: q4
manual: false
points: 2
-->

In [10]:
def parity(L):
    if isinstance(L,list) or isinstance(L,np.ndarray):
        sm = sum(L)
        if sm%2==0:
            return 0
        else:
            return 1
#
# Do not modify the following lines.
#
print(parity([0]))
print(parity([1]))
print(parity([0,1,1,1,0]))
print(parity([0,1,1,0]))
print(parity(np.array([0,1,1,1,0])))
print(parity(np.array([0,1,1,0])))

0
1
1
0
1
0


In [11]:
grader.check("q4")

q4 results: All test cases passed!

Here is how Charles Bouton would have us determine whether, if presented with some stone pile counts, a player should win or lose (assuming that the player with a winning position always plays optimally)  

- put the stone pile counts into a list
- express each number in the list in binary (with zero padding to make the binary expressions all of the same length
- write those binary expressions as rows of a matrix (call this the binary counts matrix)
- compute the parity of each *column* of the matrix

If all parities of all columns are zero, the player should lose.
If at least one column has parity 1, the player should win.

Write a function that takes a list of stone pile counts and returns the string "Win" or "Loss" as output. Call this function *win_or_loss()*.

<!--
BEGIN QUESTION
name: q5
manual: false
points: 3
-->

In [12]:
def win_or_loss(L):
    t = array_of_binary_digits_for_list_of_integers(L)
    t = t.astype(int)
    if len(t)==1:
        t = t[0]
        result = np.apply_along_axis(parity,axis=0,arr=t)
        if result==1:
            return 'Win'
        else:
            return 'Loss'
    else:
        result = np.apply_along_axis(parity,axis=0,arr=t)
        if 1 in result:
            return 'Win'
        else:
            return 'Loss'
    
#
# Do not modify the following lines.
#
print(win_or_loss([0]))
print(win_or_loss([0,0,0]))
print(win_or_loss([1,1]))
print(win_or_loss([1]))
print(win_or_loss([1,2]))
print(win_or_loss([167]))
print(win_or_loss([2,2]))

Loss
Loss
Loss
Win
Win
Win
Loss


In [13]:
grader.check("q5")

q5 results: All test cases passed!

If a player is supposed to win the game, what should be their strategy?
 
Since they are supposed to win, it is not the case that all of the columns in the binary counts matrix have zero parity, but it is not difficult to see that the player can remove stones from some pile and make that all columns in the matrix equal to zero by using **the following algorithm**:

- pick the left-most column $j$ in the binary count matrix whose parity is non-zero.
- find the first row $i$ in the binary count matrix whose entry in column $j$ is a 1
- change that $i,j$ row/column entry to a zero, and change any other entries in  row $i$ to the right of column $j$ to make the parity of every column equal to zero.

The row that was modified corresponds to one of the stone piles. The updated entries in that row tell us, in binary, how many stones are left in that pile after the player makes their move.

So now the next player is presented with a losing position (all columns have parity zero). Either 

- all piles are now empty and the game is over, or 
- there is some non-empty pile of stones

In the latter case, the player is required to pick a pile of stones and remove at least one stone from that pile. But that means that some entry in say row i, column j in the binary count matrix gets changed from a 1 to a 0, and no other entry in column $j$ changes, so the parity in column j changes to a 1 and once again, the opponent is presented with *winning* position. 

Write a function that takes as input a list of integers and returns a message that is either

- "this is a losing position" if the position is a losing position

or

- outputs the list giving the number of stones remaining in each pile after the move by the player **following the algorithm outlined above.**

Note that this is not asking for **any** move that preserves the player's winning position, but for a **specific** move.

Here, in the latter case, your output list should have the same length as your input list with the ordering of the piles remaining the same. So only one number in your list should change.

Call your function *winning_strategy()*.

<!--
BEGIN QUESTION
name: q6
manual: false
points: 3
-->

In [14]:
def winning_strategy(L):
    #print(L)
    g = array_of_binary_digits_for_list_of_integers(L)
    g = g.astype(int)
    x = np.apply_along_axis(parity,axis=0,arr=g)
    i = x.argmax()
    j = g[:,i].argmax()
    g[j,i] = 0

    for k in range(i+1,g.shape[1]):
        p_col = parity(g[:,k])
        if p_col:
            g[:,k] = 0

#     print(L,g)
    if parity(g[:,i]):
        lst = []
        for indx in range(len(g)):
            num = ''.join([str(i) for i in list(g[indx])])
            lst.append(int(num, 2))
        return lst
    else:
        return 'this is a losing position'
#
# Do not modify any of the following lines.
#
print(winning_strategy([3,4,5,6]))
print(winning_strategy([1,4,0]))
print(winning_strategy([1,0,0]))
print(winning_strategy([5,4,1]))

this is a losing position
this is a losing position
this is a losing position
[1, 4, 1]


In [15]:
grader.check("q6")

q6 results: All test cases passed!

**Final Instructions:**
1) save your notebook befor submitting it in Blackboard
2) do **not** zip your notebook 
3) do **not** change the name of your notebook


---

To double-check your work, the cell below will rerun all of the autograder tests.

In [16]:
grader.check_all()

q1 results: All test cases passed!

q2 results: All test cases passed!

q3 results: All test cases passed!

q4 results: All test cases passed!

q5 results: All test cases passed!

q6 results: All test cases passed!